apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-disk
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - name: debian-container
    image: debian
    volumeMounts:
    - name: cache-volume
      mountPath: /tmp/shared
    command: ["/bin/sh", "-c", "while true; do date >> /tmp/shared/index.html; sleep 1; done"]
  volumes:
  - name: cache-volume
    emptyDir: {} # Empty curly braces indicate default (disk-backed) storage
