apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dual-resource-hpa
spec:
  # To target a Deployment, change kind to 'Deployment' and update the name accordingly.
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vault-rolling
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10  # Scales up if average CPU > 10% of request
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10  # Scales up if average memory > 10% of request
