apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rec
spec:
  replicas: 3
  # Define the Recreate strategy here
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-rec
  template:
    metadata:
      labels:
        app: nginx-rec
    spec:
      containers:
      - name: nginx
        # Using an older version of Nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
